# Generated by Django 5.0.3 on 2024-04-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-due', '-done', '-updated', '-created']},
        ),
    ]
